name: archlinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  archlinux:

    runs-on: ubuntu-latest

    container: archlinux

    steps:
      - run: pacman -Syyuu --noconfirm
      - run: pacman -S     --noconfirm git cmake ninja gcc pkg-config curl openssl libgit2 libarchive libyaml jansson sqlite

      - uses: actions/checkout@main

      - run:  cmake --version
      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run:  ./output/bin/uppm

      - run:  ./output/bin/uppm --help
      - run:  ./output/bin/uppm --version

      - run:  ./output/bin/uppm -h
      - run:  ./output/bin/uppm -V

      - run:  ./output/bin/uppm env
      - run:  ./output/bin/uppm env -v

      - run:  ./output/bin/uppm integrate zsh

      - run:  ./output/bin/uppm update

      - run:  ./output/bin/uppm search zip

      - run:  ./output/bin/uppm depends zip
      - run:  ./output/bin/uppm depends android-sdk
      - run:  ./output/bin/uppm depends android-sdk --format=box
      - run:  ./output/bin/uppm depends android-sdk --format=dot

      - run:  ./output/bin/uppm info @all
      - run:  ./output/bin/uppm info unzip
      - run:  ./output/bin/uppm info unzip --json
      - run:  ./output/bin/uppm info unzip --yaml
      - run:  ./output/bin/uppm info unzip version
      - run:  ./output/bin/uppm info unzip license
      - run:  ./output/bin/uppm info unzip summary
      - run:  ./output/bin/uppm info unzip webpage
      - run:  ./output/bin/uppm info unzip bin-url
      - run:  ./output/bin/uppm info unzip bin-sha
      - run:  ./output/bin/uppm info unzip install
      - run:  ./output/bin/uppm info unzip formula

      - run:  ./output/bin/uppm fetch   gzip
      - run:  ./output/bin/uppm fetch   gsed -v

      - run:  ./output/bin/uppm install unzip

      - run:  ./output/bin/uppm info unzip installed-dir
      - run:  ./output/bin/uppm info unzip installed-files
      - run:  ./output/bin/uppm info unzip installed-receipt-path
      - run:  ./output/bin/uppm info unzip installed-receipt-json
      - run:  ./output/bin/uppm info unzip installed-receipt-yaml
      - run:  ./output/bin/uppm info unzip installed-timestamp-unix
      - run:  ./output/bin/uppm info unzip installed-timestamp-iso-8601
      - run:  ./output/bin/uppm info unzip installed-timestamp-rfc-3339
      - run:  ./output/bin/uppm info unzip installed-version

      - run:  ./output/bin/uppm tree unzip
      - run:  ./output/bin/uppm tree unzip -L 3

      - run: |
          sed -i '/^version: /c version: 6.0.28' $(./output/bin/uppm info unzip formula | head -n 1 | cut -d ' ' -f2)

      - run:  ./output/bin/uppm ls-available
      - run:  ./output/bin/uppm ls-installed
      - run:  ./output/bin/uppm ls-outdated

      - run:  ./output/bin/uppm is-available curl
      - run:  ./output/bin/uppm is-installed unzip
      - run:  ./output/bin/uppm is-outdated  unzip

      - run:  ./output/bin/uppm upgrade   unzip
      - run:  ./output/bin/uppm reinstall unzip
      - run:  ./output/bin/uppm uninstall unzip

      - run:  ./output/bin/uppm upgrade-self

      - run:  ./output/bin/uppm formula-repo-list
      - run:  ./output/bin/uppm formula-repo-add my_repo https://github.com/leleliu008/uppm-formula-repository-my_repo
      - run:  ./output/bin/uppm formula-repo-del my_repo

      - run:  ./output/bin/uppm cleanup
